defaults:
  - log_mel_spectrogram@log_mel_spectrogram_conf: log10_mel_spectrogram
  - f0_estimator@f0_estimator_conf: pyin_g1_g5
  - frame_content_feature_extractor@frame_content_feature_extractor_conf: nemo_stt_conformer
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
audio_root_folder: ???
audio_rglob_pattern: "*.wav"
sample_rate: 22050
stages:
  - compute_log_mel_and_loudness
  - compute_f0
  - compute_frame_content
  - compute_speaker_embedding
# log mel & loudness
log_mel_name_suffix: log_mel
loudness_name_suffix: loudness
log_mel_spectrogram_conf:
  sample_rate: ${sample_rate}
# f0
f0_name_suffix: f0
f0_estimator_conf:
  sample_rate: ${sample_rate}
# frame content
frame_content_name_suffix: frame_content
frame_content_feature_extractor_conf:
  sample_rate: ${sample_rate}
# speaker_embedding
speaker_embedding_name_suffix: speaker_embedding
speaker_embedding_model_conf:
  _target_: igoose.tasks.backbones.kmic_demo_2023q2.speaker_embedding_models.PretrainedSpeakerEmbeddingBackbone
  sample_rate: ${sample_rate}
